### ISSUE TITLE
Error "Symbol’s function definition is void: first"

### ISSUE THREAD

**Issue by andreasklostermaier** [theodorewiles/org-mind-map#15]
This error comes up, if any line in the document contains a URL with a trailing "/".

Examples:
```
- Test this: https://www.indiehackers.com/forum/, foo.
- [[https://www.indiehackers.com/forum/][Indiehackers]]
```
will produce the error,
```
- Test this: https://www.indiehackers.com/forum, foo.
- [[https://www.indiehackers.com/forum][Indiehackers]]
```
will not produce the error.

**Comment by the-ted** [comment]
I fixed this error by excluding non-html links from being checked for headlines.
