### ISSUE TITLE
Can not deal with other language such as Chinese.

### ISSUE THREAD

**Issue by liuzy** [theodorewiles/org-mind-map#18]
When I use it to deal with file which has Chinese in the Items, It just consider different items the same one. Can you give a look of this instance?

**Comment by damon98xp** [comment]
Do we have any ideas or updates for this issue?

**Comment by damon98xp** [comment]
This gives node w/ chinese support w/ microsoft 雅黑體
1. Add font support
(add-to-list 'org-mind-map-default-node-attribs '("fontname" . "microsoft yahei"))
2. Add Chinese filter in regexp in the function
(defun org-mind-map-dot-node-name (s)
  "Make string S formatted to be usable within dot node names."
  (replace-regexp-in-string
;;;   "[^A-Za-z0-9]" ""   <-  UPDATE THIS REGEXP
   "[^\u4e00-\u9fa5A-Za-z0-9]" ""
   (replace-regexp-in-string
    "</?\\(table\\|tr\\|td\\)[^<>]*>" ""
    (replace-regexp-in-string "label=\\(\"[^\"]+\"\\|[^,]+\\).*" "\\1" s))
   nil t))
3. Save org file in UTF-8 format, and the code works fine for me.

**Comment by kenhuang-io** [comment]
Hi, another way to fix it is by embracing node name within double quotes, see PR #29

**Comment by the-ted** [comment]
Thanks - just merged in.
