### ISSUE TITLE
Links between nodes

### ISSUE THREAD

**Issue by putzel** [theodorewiles/org-mind-map#20]
On GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) links between nodes are not working for the example5.

**Comment by kprojiang** [comment]
I have the same problem, on Win7 Emacs 24.5.

**Comment by bingoUV** [comment]
Yes, links not working at all.  PDF attached - no links created in the diagram even if verbatim org file is taken from Readme.

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars) of 2018-06-16
Graphviz 2.38.0

[x_diagram.pdf](https://github.com/theodorewiles/org-mind-map/files/2232539/x_diagram.pdf)

`(org-mind-map-get-links nil)` takes the cursor to the top of the buffer, and prints a message 

>  Position saved to mark ring, go back with ‘C-c &’.

**Comment by the-ted** [comment]
I believe I have fixed this issue.

**Comment by bubak4** [comment]
For me, it does not work -- result for example file is the same as or @bingoUV.

Configuration:
```
        (use-package org-mind-map
            :ensure t
            :init
            (require 'ox-org)
            :config
            (progn
                (setq
                    org-mind-map-engine "dot"
                    org-mind-map-wrap-legend-line-length 50
                    org-mind-map-wrap-line-length 60)))))
```

Emacs version (debian stable default): GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian

Org version (latest from melpa): Org mode version 9.1.14 (9.1.14-9-g131531-elpa @ /home/martin/.emacs.d/elpa/org-20181119/)

Org-Mind-Map version (latest from melpa): 20180826.2340

**Comment by laheadle** [comment]
please reopen

**Comment by bubak4** [comment]
Hi,

I would if I could :-)

Since I am not collaborator on your project (I'd be a poor one :-) -- I
am unable to re-open the issue, only create a new one -- or re-open
issues that I have filed, which is not the case
(https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github).

Kind Regards,

Lyn Headley <notifications@github.com> writes:

> please reopen
>
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/theodorewiles/org-mind-map/issues/20#issuecomment-442960644
-- 
Martin Šlouf
https://martin.slouf.name/
