### ISSUE TITLE
Where do you put TB to change to vertical orientation?

### ISSUE THREAD

**Issue by academikuser** [theodorewiles/org-mind-map#4]
I tried eval-defun

    `(defcustom org-mind-map/rankdir "TB" "sentence") `

and as a tag

* node                 :tb:
** sub                  :tb:

**Comment by the-ted** [comment]
I do that by M-x customize-group; org-mind-map; then, set the option for "Org Mind Map/Rankdir" to "Top to bottom". I believe you should also be able to do: (setq org-mind-map/rankdir "TB") in your .emacs
