### ISSUE TITLE
Homepage link on repository returns 404

### ISSUE THREAD

**Issue by huseyinyilmaz** [theodorewiles/org-mind-map#5]
Hello,

First of all thank you for the project. It seems like I can just use org-mode for graph generation from now on :)

I just wanted to tell you one small link problem on repo. When I open this project from packages list, I got following page:

https://cl.ly/3o451R1b1Q1y

It would probably be better to link directly to repository home page rather than the file.

**Comment by the-ted** [comment]
Fixed URL included in preamble
