### ISSUE TITLE
Can't export to pdf

### ISSUE THREAD

**Issue by galegria** [theodorewiles/org-mind-map#8]
When running the first basic example (and all the others) I get in emacs (Terminal or standalone) a: 
`Symbol’s function definition is void: first` 

I am using El Capitan 10.11.6 (15G31), emacs Version 25.2 (9.0) from homebrew. (graphviz as well).

Running emacs with `emacs -nw --debug-init` produces no additional info

**Comment by andreasklostermaier** [comment]
I can confirm this. I am using
- Ubuntu 17.04
- Emacs 25.3.2
- Graphviz 2.38.0
- org-mind-map Version 20170912.1411 (installed via Melpa)

and get
`Symbols's function definition is void: first`
on all org-mode-files.

**Comment by nocaoper** [comment]
Found a temporary solution and proposed a pull request. Before the fix you can temporarily fix this yourself.

1. go to your home directory type
cd
2. go to the place where your plugin was downloaded as for me
cd .emacs.d/elpa/
3. change directory to the org-mind-map plugin
cd org-mind-map-20170912.1411
4. disable the cached .elc by renaming org-mind-map.elc
mv org-mind-map.elc old.elc
5. apply the fix on the plugin main file which is org-mind-map.el
replace "first x" by "nth 0 x"
replace "first x" by "nth 1 x"
6. save and reload emacs
7. You're done!

**Comment by andreasklostermaier** [comment]
I can confirm, nocaoper's quick fix is working, but:

there is a typo in the replace-commands, they should read:

replace "first x" by "nth 0 x"
replace **"second** x" by "nth 1 x"
